language: go
sudo: false

env:
  global:
    - GITHUB_REPO: opencobra/cobrapy
    - HUGO_VER: 0.29
    - HUGO_DIR: public

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_${HUGO_VER}_Linux-64bit.tar.gz -O hugo.tar.gz
  - tar xvzf hugo.tar.gz

script:
  - ./hugo -d "${HUGO_DIR}"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: $GITHUB_REPO
  local_dir: $HUGO_DIR
  on:
    branch: master

notifications:
  email:
    on_sucess: never
    on_failure: always
